#!/bin/sh

mkdir -p opk
cp ./heboris.elf opk/heboris.elf
cp ./icon.png opk/icon.png
cp -r ./res opk/

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Heboris
Comment=Puzzle game
Exec=heboris.elf
Icon=icon
Terminal=false
Type=Application
Categories=games;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

mksquashfs ./opk heboris_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
